### ISSUE TITLE
A problem about paper

### ISSUE THREAD

**Issue by Huangpq2019** [dparks1134/UniteM#1]
Does this software have related articles to describe specific algorithm ideas and details?
If does, could you tell me? If not, colud you show more details about the algorithm for me?
Thanks!

**Comment by donovan-h-parks** [comment]
Hi. Sorry for the slow reply. I do have an unpublished manuscript I can send you. Can you email me at donovan.parks [at] gmail.com and I will send you the manuscript?

**Comment by dparks1134** [comment]
Hi. Sorry for the slow reply. I do have an unpublished manuscript I can send you. Can you email me at donovan.parks [at] gmail.com and I will send you the manuscript?
